### ISSUE TITLE
[PE-D][Tester D] Output box too small and unsuitable for fast-typers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F11-2/tp#179]
**Describe the bug**
* Minor cosmetic issue
* The output command box is too small and not suitable for fast-typers.

**To reproduce:**
* Type in guest add in the input box

![Untitled.png](https://raw.githubusercontent.com/jovkusuma/ped/main/files/51bbd15e-7779-4490-a390-bffd64ec674a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: jovkusuma/ped#1

**Comment by keaganpzh** [comment]
Update UG to mention a larger output box in planned enhancements. Meanwhile, users can enlarge their screens.
