### ISSUE TITLE
[PE-D][Tester B] Overly long domain name is accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F11-2/tp#190]
Should have either a warning or a blocking of such possible domains.

![image.png](https://raw.githubusercontent.com/Saezenn/ped/main/files/276a6df4-fd00-4dd2-9473-f757ed88b6d2.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Saezenn/ped#3

**Comment by keaganpzh** [comment]
Update email input constraints to accept long domain names in UG.

**Comment by wasjoe1** [comment]
6) Overly long domain name is accepted ⇒ tbh why not? but sure warning works
