### ISSUE TITLE
[PE-D][Tester B] Overly generalised error statements

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F11-2/tp#193]
Error messages are overly generalised. Very difficult to tell what is wrong. Does not flag out obvious mistake inputs like typing email/ instead of e/, or /e instead or e/.

![image.png](https://raw.githubusercontent.com/Saezenn/ped/main/files/8f764020-23ab-490a-b9fa-1ed1cbd21456.png)

![image.png](https://raw.githubusercontent.com/Saezenn/ped/main/files/7ff67a55-ea8b-4437-978d-7c651d6261cd.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Saezenn/ped#4

**Comment by wasjoe1** [comment]
7) Overly generalised error statements ⇒ not sure if its a bug, probably low priority
