### ISSUE TITLE
[PE-D][Tester B] Needless case sensitivity used

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-2/tp#196]
commands like p/ , e/, etc are needlessly case sensitive. Restricts the usability of the application.

![image.png](https://raw.githubusercontent.com/Saezenn/ped/main/files/b9847b80-f5eb-4c4e-be80-c014d27658fc.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Saezenn/ped#6

**Comment by keaganpzh** [comment]
Can add a footnote in the UG or something, this doesn't seem very valid to me.
