### ISSUE TITLE
[PE-D][Tester C] Table form for appendix to improve readability 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-2/tp#203]
I suggest using a table form (one column for parameter type, then one column for acceptable values) in order to increase readability.
![image.png](https://raw.githubusercontent.com/jamesebond/ped/main/files/22bc22e1-ae08-4b67-9123-407e8ff36731.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jamesebond/ped#8

**Comment by p-xp** [comment]
Closed, will be implemented together with the fix for #218.
