### ISSUE TITLE
[PE-D][Tester B] Foreign country numbers not accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F11-2/tp#205]
Vendors/Applicants can have overseas mobile numbers. '+' sign should be allowed.
![image.png](https://raw.githubusercontent.com/Saezenn/ped/main/files/ba2944d5-2bbb-4eb0-ac8f-c3ae57a937ad.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Saezenn/ped#10

**Comment by wasjoe1** [comment]
currently a feature flaw, can put in future enhancements

**Comment by keaganpzh** [comment]
Resolved by #238.
