### ISSUE TITLE
[PE-D][Tester D] Add command does not run with invalid integer value

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F11-2/tp#212]
**Describe the bug:**
* If you input an extreme integer value which is over the boundaries of integer bits, it does not want to run even after enter is pressed

**To reproduce**
* Try adding a new guest add command with the invalid table number that exceeds 32 bits

**Expected behavior**
* Throw an error which mentions something like Invalid number, or give a range of valid numbers

![Screenshot 2023-11-03 at 5.11.46 PM.png](https://raw.githubusercontent.com/jovkusuma/ped/main/files/6d368e0b-d755-4086-90be-3ee0cc94495c.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: jovkusuma/ped#7

**Comment by keaganpzh** [comment]
Fix number format exception when parsing table number.
