### ISSUE TITLE
[PE-D][Tester B] Colour contrast

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-2/tp#216]
Colour constrast for food requirement is very hard to see
![image.png](https://raw.githubusercontent.com/Saezenn/ped/main/files/d01ac9ee-311d-40cc-8b75-5504f70c44e4.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Saezenn/ped#13

**Comment by wasjoe1** [comment]
not sure if this is an issue? could discuss how we want to handle this, be it enhanced implementation or just ignore

**Comment by keaganpzh** [comment]
Resolved by #238.
