### ISSUE TITLE
Update Model

### ISSUE THREAD

**Issue by keaganpzh** [AY2324S1-CS2103T-F11-2/tp#27]
Change model.AddressBook to include – GuestList that stores Guests, and VendorList that stores Vendors
- Originally in the code, this is UniquePersonList
- For now, we can just use UniquePersonList for the guest list and vendor list
- E.g. UniquePersonList guestList = new UniquePersonList();

**Comment by samuelim01** [comment]
After looking into the code, we are unable to use `UniquePersonList` directly. For example, the `AddressBook::setVendor(Vendor, Vendor)` method is dependent on `UniqueVendorList::setVendor(Vendor, Vendor)`. This would not be possible with the `UniquePersonList` class.

**Comment by samuelim01** [comment]
After some discussion with @p-xp, this issue has been split into two separate issues (guests and vendors). They can be found below:
Add `guests` to `AddressBook`: #43 
Add `vendors` to `AddressBook`: #44
